apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: req-nlp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: req-nlp:latest
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source